/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package partyplanner;

/**
 *
 * @author BlaineKillen
 */
public class PartyPlannerUI extends javax.swing.JFrame {

    /**
     * Creates new form PartyPlannerUI
     */
    public PartyPlannerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        wings = new javax.swing.JLabel();
        sticks = new javax.swing.JLabel();
        cupcakes = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Party Planner");

        jLabel2.setText("Number of people:");

        jLabel3.setText("Wings? type yes or no:");

        jLabel4.setText("Mozzarella sticks? type yes or no:");

        jLabel5.setText("Cupcakes? type yes or no:");

        jTextField1.setText("0");

        jButton1.setText("Request food amounts");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        wings.setText("Result Wings");

        sticks.setText("Result Mozarella Sticks");

        cupcakes.setText("Result Cupcakes");

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(140, 140, 140)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(wings)
                        .add(24, 24, 24)
                        .add(sticks)
                        .add(33, 33, 33)
                        .add(cupcakes))
                    .add(layout.createSequentialGroup()
                        .add(64, 64, 64)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(jLabel3)
                                .add(jLabel2)
                                .add(jLabel4)
                                .add(jLabel5))
                            .add(jButton1))
                        .add(40, 40, 40)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jTextField4)
                            .add(jTextField3)
                            .add(jTextField2)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(9, 9, 9)
                                .add(jButton2)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 26, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2))
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(wings)
                    .add(sticks)
                    .add(cupcakes))
                .add(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        numPeople = Integer.parseInt(jTextField1.getText());
        
        wingsflag = jTextField2.getText();
        sticksflag = jTextField3.getText();
        cupcakeflag = jTextField4.getText();
        
        // asssign bolean values based on yes or no
        if (wingsflag.equals("yes"))
         {
             isWings = true;
         }
        else
         {
             isWings = false;
         }   
        
        if (sticksflag.equals("yes"))
         {
             isSticks = true;
         }
        else
         {
             isSticks = false;
         }   
        
        if (cupcakeflag.equals("yes"))
         {
             isCupcakes = true;
         }
        else
         {
             isCupcakes = false;
         }   
        
        
        // calulate values
        if ((isWings == true) && (isSticks == false) && (isCupcakes == false))
        {
            numWings = numPeople * 6;
        }
        
        if ((isWings == false) && (isSticks == true) && (isCupcakes == false))
        {
            numSticks = numPeople * 5;
        }
        
        if ((isWings == true) && (isSticks == true))
        {
            numWings = numPeople * 4;
            numSticks = numPeople * 3;
        }
        
        if (isCupcakes == true)
            
        {
              if ( (isWings == false) && (isSticks == false) )
                {
                    numCupcake = numPeople * 2;
                }
        
              if ( (isWings == true) || (isSticks == true) )        
                {
                    numCupcake = numPeople * 1;
                }
        }
        
        //convert results to strings and display
        wings.setText("Wings: " + String.valueOf(numWings));
        sticks.setText("Mozarella Sticks: " + String.valueOf(numSticks));
        cupcakes.setText("Cupcakes: " + String.valueOf(numCupcake));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        jTextField1.setText("0");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        
        wings.setText("Result Wings");
        sticks.setText("Result Mozarella Sticks");
        cupcakes.setText("Result Cupcakes");
        
        numWings = 0;
        numCupcake = 0;
        numSticks = 0;
        
    }//GEN-LAST:event_jButton2ActionPerformed

    int numPeople, numWings, numSticks, numCupcake;
    
    String wingsflag, sticksflag, cupcakeflag;
    
    boolean isWings,isSticks, isCupcakes;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartyPlannerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartyPlannerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartyPlannerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartyPlannerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PartyPlannerUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cupcakes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel sticks;
    private javax.swing.JLabel wings;
    // End of variables declaration//GEN-END:variables
}
