/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tickets;

import java.text.*;

/**
 *
 * @author BlaineKillen
 */
public class TicketsUI extends javax.swing.JFrame {

    /**
     * Creates new form TicketsUI
     */
    public TicketsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Basketball = new javax.swing.JTextField();
        AddBasketball = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Lax = new javax.swing.JTextField();
        AddLax = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Checkout = new javax.swing.JButton();
        Total = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Dome Ticket Shop");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Womens Sports");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter number Basketball Tickets");

        jLabel3.setText("(Mens $25, Womens $20)");

        Basketball.setText("0");

        AddBasketball.setText("Add to Cart");
        AddBasketball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBasketballActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter number Lacross Tickets");

        jLabel5.setText("(Mens $12, Womens $10)");

        Lax.setText("0");

        AddLax.setText("Add to Cart");
        AddLax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLaxActionPerformed(evt);
            }
        });

        Checkout.setText("Checkout");
        Checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutActionPerformed(evt);
            }
        });

        Total.setText("Total");

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Mens Sport");

        jLabel6.setText("You Ordered:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(49, 49, 49)
                                .add(jLabel3))
                            .add(layout.createSequentialGroup()
                                .add(30, 30, 30)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel4)
                                    .add(jLabel2))))
                        .add(51, 51, 51)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(Basketball, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .add(Lax))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(AddBasketball))
                            .add(layout.createSequentialGroup()
                                .add(AddLax)
                                .add(0, 0, Short.MAX_VALUE))))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(56, 56, 56)
                                .add(jRadioButton1)
                                .add(30, 30, 30)
                                .add(jRadioButton2))
                            .add(layout.createSequentialGroup()
                                .add(185, 185, 185)
                                .add(jLabel1))
                            .add(layout.createSequentialGroup()
                                .add(58, 58, 58)
                                .add(jLabel5))
                            .add(layout.createSequentialGroup()
                                .add(38, 38, 38)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 456, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(Checkout)
                                            .add(Clear))
                                        .add(152, 152, 152)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel10)
                                            .add(jLabel7)
                                            .add(jLabel6)
                                            .add(jLabel8)
                                            .add(jLabel9)))))
                            .add(layout.createSequentialGroup()
                                .add(48, 48, 48)
                                .add(Total)))
                        .add(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton2)
                    .add(jRadioButton1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(Basketball, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(AddBasketball))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(Lax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(AddLax))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(54, 54, 54)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Checkout)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel7)
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Total)
                    .add(jLabel8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(jLabel9)
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Clear)
                    .add(jLabel10))
                .add(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    double totalpricetickets = 0.0;
    
    int mensLaxTickets, womensLaxTickets, mensBasketballTickets, womensBasketballTickets;
    
    private void AddBasketballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBasketballActionPerformed
        // TODO add your handling code here:
        int numBasketball;
        
        numBasketball = Integer.parseInt(Basketball.getText());
        
        if (jRadioButton1.isSelected() == true)
        {
            mensBasketballTickets = numBasketball + mensBasketballTickets;
            addTickets(numBasketball,25);
        }
        else{
            if (jRadioButton2.isSelected() == true)
            {
                womensBasketballTickets = numBasketball + womensBasketballTickets;
                addTickets(numBasketball,20);
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Please select the sports gender");
            }
        }
        
        
    }//GEN-LAST:event_AddBasketballActionPerformed

    private void AddLaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLaxActionPerformed
        // TODO add your handling code here:
        int numLax;
        
        numLax = Integer.parseInt(Lax.getText());
        
        if (jRadioButton1.isSelected() == true)
        {
            addTickets(numLax,12);
            mensLaxTickets = mensLaxTickets + numLax; 
        }
        else{
            if (jRadioButton2.isSelected() == true)
            {
                addTickets(numLax,10);
                womensLaxTickets = womensLaxTickets + numLax; 
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Please select the sports gender");
            }
        }
        
    
    }//GEN-LAST:event_AddLaxActionPerformed

    private void CheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutActionPerformed
        // TODO add your handling code here:
        NumberFormat cf = NumberFormat.getCurrencyInstance();
        
        Total.setText(cf.format(totalpricetickets));
        
        jLabel7.setText(String.valueOf(mensBasketballTickets) + " Men's Basketball Tickets");
        jLabel8.setText(String.valueOf(womensBasketballTickets) + " Women's Basketball Tickets");
        jLabel9.setText(String.valueOf(mensLaxTickets) + " Men's Lacrosse Tickets");
        jLabel10.setText(String.valueOf(womensLaxTickets) + " Women's Lacrosse Tickets");
        
    }//GEN-LAST:event_CheckoutActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        totalpricetickets = 0;
        Total.setText("Total");
        
        mensBasketballTickets = 0;
        womensBasketballTickets = 0;
        mensLaxTickets = 0;
        womensLaxTickets = 0;
        
        Basketball.setText("0");
        Lax.setText("0");
        
        buttonGroup1.clearSelection();
        
        jLabel7.setText("");
        jLabel8.setText("");
        jLabel9.setText("");
        jLabel10.setText("");
        
    }//GEN-LAST:event_ClearActionPerformed

    private void addTickets(int numTickets, double price)
    { 
        totalpricetickets = totalpricetickets + numTickets * price;  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TicketsUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBasketball;
    private javax.swing.JButton AddLax;
    private javax.swing.JTextField Basketball;
    private javax.swing.JButton Checkout;
    private javax.swing.JButton Clear;
    private javax.swing.JTextField Lax;
    private javax.swing.JLabel Total;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
