/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package onlineadreports;

import java.io.*;
import java.util.Scanner;
import javax.swing.*;

/**
 *
 * @author BlaineKillen
 */
public class OnlineAdReportsUI extends javax.swing.JFrame {

    /**
     * Creates new form OnlineAdReportsUI
     */
    public OnlineAdReportsUI() {
        initComponents();
    }

    //initialize object array and company counter
    Company companyArray [] = new Company [20];
    int numCompany; 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Select a File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Read File Status");

        jLabel2.setText("Google");

        jLabel3.setText("Yahoo");

        jLabel8.setText("Local");

        jLabel9.setText("National");

        jButton2.setText("Write File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Both");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton1)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(206, 206, 206)
                                    .add(jLabel5)
                                    .add(168, 168, 168)
                                    .add(jLabel6)
                                    .add(365, 365, 365)
                                    .add(jLabel7))
                                .add(layout.createSequentialGroup()
                                    .add(18, 18, 18)
                                    .add(jLabel1)))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(50, 50, 50)
                                .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 221, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 203, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(194, 194, 194)
                                .add(jButton2))
                            .add(layout.createSequentialGroup()
                                .add(204, 204, 204)
                                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 193, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(52, 52, 52)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jLabel1))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel8)
                    .add(jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jLabel6)
                    .add(jLabel7))
                .add(44, 44, 44)
                .add(jButton2)
                .add(49, 49, 49)
                .add(jLabel4)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //initialize variables
        String companyName = "", searchEngine = "", campaign = "", 
                google = "<html>Google: <p>", yahoo = "<html>Yahoo: <p>", 
                local= "<html>Local: <p>", national = "<html>National: <p>", both = "<html>Both: <p>";
        int keyword = 0, month1 = 0, month2 = 0, month3 = 0, count = 0;
        
    //Create a file chooser
final JFileChooser fc = new JFileChooser();
//In response to a button click:
int returnVal = fc.showOpenDialog(null);
fc.setCurrentDirectory(new java.io.File("src/Resources"));
 
   
         //open and perform the reader
         try
        {
           // open the file and set up the scanner 
            BufferedReader in = new BufferedReader(new
                   FileReader(fc.getSelectedFile().getPath())); 
            Scanner sc = new Scanner(in);
            // use comma as a delimiter 
                   sc.useDelimiter(",|(\\n|\\r)+");
                   
           while (sc.hasNext())
           {
               if (sc.hasNext()) 
               {
                       companyName = sc.next();    
               }
               
               if (sc.hasNext()) 
               {
                       campaign = sc.next();
               }
               
               if (sc.hasNextInt())
               {
                       keyword = sc.nextInt();
               } 
               
               
               if (sc.hasNext()) 
               {
                       searchEngine = sc.next();   
               }
                          
                    
               if (sc.hasNextInt())
               {
                        month1 = sc.nextInt();
               }
               
               if (sc.hasNextInt())
               {
                        month2 = sc.nextInt();
               }
               
               if (sc.hasNextInt())
               {
                        month3 = sc.nextInt();
               }
               
           
            // calls the constructor
            Company info = new Company(companyName, campaign, keyword, searchEngine, month1, month2, month3);   
            
            companyArray [count] = info; 
            
            count++;
            
           }
           
           //close the counter and display status
           numCompany = count;
           
           sc.close();
           
           jLabel1.setText("Done reading file");
           
           
                   
        }    
        
        catch (Exception e)
        {
            System.out.println(e.toString());       
        }        
        
        //fill the google and yahoo variables and display them 
        for (int i = 0; i < numCompany; i++)
        {
            if (companyArray[i].searchengine.equals("google"))
            {
                google = google + "<p>" + companyArray[i].toString();
            }  
            if (companyArray[i].searchengine.equals("yahoo"))
            {
                yahoo = yahoo + "<p>" + companyArray[i].toString();
            } 
            if (companyArray[i].searchengine.equals("both"))
            {
                both = both + "<p>" + companyArray[i].toString();           
            } 
        }
        
        //fill the local and natioanl variables and display them
        for (int i = 0; i < numCompany; i++)
        {
            if (companyArray[i].campaign.equals("local"))
            {
                local = local + "<p>" + companyArray[i].toString();
            }  
            if (companyArray[i].campaign.equals("national"))
            {
                national = national + "<p>" + companyArray[i].toString();
            } 
            if (companyArray[i].campaign.equals("both"))
            {
                local = local + "<p>" + companyArray[i].toString();
                national = national + "<p>" + companyArray[i].toString();             
            } 
        }
        
        //display the variables
        jLabel2.setText(google);
        jLabel3.setText(yahoo);
        jLabel4.setText(both);
        
        jLabel8.setText(local);
        jLabel9.setText(national);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
 
final JFileChooser sc = new JFileChooser();
//In response to a button click:
int returnVal = sc.showOpenDialog(null);        
int totalclicks = 0;        
        
for (int i = 0; i < numCompany;i++)
{
    totalclicks = totalclicks + companyArray[i].sumClicks();
}    
         try {
            
            //Construct the BufferedWriter object
            BufferedWriter writeout = new BufferedWriter(new FileWriter(sc.getSelectedFile().getPath()));
            
            //Start writing to the output stream
            writeout.write("'Premium' Companies");
            writeout.newLine();
            writeout.write("Total clicks: " + totalclicks);
            writeout.newLine();
            writeout.write("");
            writeout.newLine();
            writeout.write("");

//test all the objects and writte the premium ad campaigns to the file
for (int i = 0; i <numCompany; i++)
{
    if (companyArray[i].isPremium(companyArray[i].campaign, companyArray[i].keyword, companyArray[i].sumClicks()) == true)
    {
        writeout.write(companyArray[i].toString());
        writeout.newLine();
    }    
    
}    
         // close the buffer writer
         writeout.flush();
         writeout.close();
         
         }            
            
        
        catch (FileNotFoundException ex) {
            ex.printStackTrace();}
        catch (IOException ex) {
            ex.printStackTrace();
        } 
    
   
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnlineAdReportsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnlineAdReportsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnlineAdReportsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnlineAdReportsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new OnlineAdReportsUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
