/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentdata;

import java.io.*;
import java.util.Scanner;
import javax.swing.*;

/**
 *
 * @author BlaineKillen
 */
public class StudentDataUI extends javax.swing.JFrame {

    /**
     * Creates new form StudentDataUI
     */
    public StudentDataUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileRead = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileRead.setText("Read Student File");
        FileRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileReadActionPerformed(evt);
            }
        });

        jLabel1.setText("File Status");

        jButton2.setText("Display Students");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Results:");

        jButton1.setText("Display Tallest Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tallest:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter (partial) search names ");

        jLabel5.setText("Result");

        jButton4.setText("Sort Students by age:");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText("By Age:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jButton1)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jButton2)
                                .add(FileRead))
                            .add(layout.createSequentialGroup()
                                .add(jButton3)
                                .add(23, 23, 23)))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 364, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3)
                            .add(layout.createSequentialGroup()
                                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(33, 33, 33)
                                .add(jLabel4))))
                    .add(layout.createSequentialGroup()
                        .add(83, 83, 83)
                        .add(jButton4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel6)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 323, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(36, 36, 36)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(FileRead)
                    .add(jLabel1))
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jLabel2))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jLabel3))
                .add(44, 44, 44)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3)
                    .add(jLabel4))
                .add(30, 30, 30)
                .add(jLabel5)
                .add(33, 33, 33)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton4)
                    .add(jLabel6))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Student [] studentArray = new Student [50];
    
    int numStudents;
    
    private void FileReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileReadActionPerformed
        // TODO add your handling code here:
        int count = 0;
        
        String studentname = "", gender = "", oneline;
        int age = 0, height = 0, numsales = 0;
        
        
        try
        {
           // open the file and set up the scanner 
            BufferedReader in = new BufferedReader(new
                   FileReader("src/Resources/studentFile.txt")); 
            Scanner sc = new Scanner(in);
            // use comma as a delimiter 
                   sc.useDelimiter(",|(\\n|\\r)+");
                   
           while (sc.hasNext())
           {
               if (sc.hasNext()) {
                        studentname = sc.next();
                        //System.out.println("item 1 " + person);
                    }
                if (sc.hasNext()) {
                        gender = sc.next();
                        //System.out.println("item 2 " + candy);
                    }
                if (sc.hasNextInt()) {
                        age = sc.nextInt();
                        //System.out.println("item 3 " + numcandy);
                    }
               if (sc.hasNext())
               {
                        height = sc.nextInt();
               }
           
            // calls the constructor
            Student info = new Student(studentname, gender, age, height);   
            
            studentArray [count] = info; 
            
            count++;
           }
           
           numStudents = count;
           
           sc.close();
           
           jLabel1.setText("Done reading file");
           
           
                   
        }    
        
        catch (Exception e)
        {
            System.out.println(e.toString());       
        }        
    }//GEN-LAST:event_FileReadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String message = "<html>Student Info: <p>";
        // variable for each candy sale item
        Student oneStudent;

        // loop over all defined items in the sales array
        //    adding each item to the message string
        for (int i = 0; i < numStudents; i++) {
            oneStudent = studentArray[i];
            message = message + "<p>"  + studentArray[i].toString();
        }
        // display the resulting message string
        jLabel2.setText(message);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int tallest = 0;
        String name= "";
        
        for (int i = 0; i < numStudents; i++)
        {
            if (studentArray[i].getHeight() > tallest)
            {
                tallest = studentArray[i].getHeight();
                name = studentArray[i].getStudentName();
                       
            } 
            
            if (studentArray[i].getHeight() == tallest)
            {
                
                if (name.equals(studentArray[i].getStudentName()))
                {    
                
                }
                else
                {
                    name = name + " " + studentArray[i].getStudentName();
                }    
                
            }    
        } 
        
        jLabel3.setText(name);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String search = jTextField1.getText();
        String display = "<html>Student Info: <p>";
        
        for (int i = 0; i < numStudents; i++)
        {
            
            if (studentArray[i].getStudentName().startsWith(search))
            {
                display = display + "<p>"  + studentArray[i].toString();
            }    
            
        }
        
        jLabel5.setText(display);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        int n = numStudents; // n is the length of the array
        
        for (int i = 0; i < (n-1); i++) // if array has n elements, number of passes is n-1 
        {
                for (int j = 0; j < (n - (i+1)) ; j++)   
                {
                        if (studentArray[ j ].getAge() > studentArray [ j + 1].getAge()) 
                        {
                                Student temp = studentArray [ j ];
                                studentArray [ j ] = studentArray [ j + 1]; 
                                studentArray [ j + 1] = temp;
                        } 
                }
                        
        }
        // end of sorting 
        
        String display = "<html>By Age: <p>";
        
        for (int i = 0; i < numStudents; i++) {
            
            display = display + "<p>"  + studentArray[i];
        }
        // display the resulting message string
        jLabel6.setText(display);
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StudentDataUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FileRead;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
