/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalcar;

import java.text.*;
/**
 *
 * @author BlaineKillen
 */
public class RentalCarUI extends javax.swing.JFrame {

    /**
     * Creates new form RentalCarUI
     */
    public RentalCarUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        days = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        coupon = new javax.swing.JTextField();
        compute = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fee = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        computeEverything = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Basic = new javax.swing.JLabel();
        options = new javax.swing.JLabel();
        gas = new javax.swing.JLabel();
        subtotal = new javax.swing.JLabel();
        tax = new javax.swing.JLabel();
        totalrental = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome to");

        jLabel2.setText("Krazy Kars Rental Company");

        jLabel3.setText("Name:");

        jLabel4.setText("Number of Days:");

        jLabel5.setText("Select a car:");

        days.setText("0");
        days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Economy");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Mid-Size");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Luxury");

        jLabel6.setText("Enter Coupon Code if you have one:");

        coupon.setText("0");

        compute.setText("Show fee");
        compute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeActionPerformed(evt);
            }
        });

        jLabel7.setText("Fee is:");

        jCheckBox1.setText("GPS System");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Extra Insurance");

        jCheckBox3.setText("Child Safety Seat");

        jLabel8.setText("Select Options");

        jLabel9.setText("Bring Back with full tank?");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Yes");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("No");

        computeEverything.setText("Compute Total");
        computeEverything.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeEverythingActionPerformed(evt);
            }
        });

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        jLabel10.setText("Basic Fee:");

        jLabel11.setText("Options:");

        jLabel12.setText("Gas:");

        jLabel13.setText("Subtotal:");

        jLabel14.setText("Sales Tax:");

        jLabel15.setText("Total Rental:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(jLabel5)
                                .add(18, 18, 18)
                                .add(jRadioButton1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jRadioButton2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jRadioButton3))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jLabel4))
                                .add(82, 82, 82)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(days, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel8)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(layout.createSequentialGroup()
                                            .add(53, 53, 53)
                                            .add(compute)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel7))
                                        .add(jLabel6)))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(27, 27, 27)
                                        .add(coupon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(18, 18, 18)
                                        .add(fee))))
                            .add(layout.createSequentialGroup()
                                .add(jCheckBox1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jCheckBox2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jCheckBox3))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createSequentialGroup()
                                        .add(47, 47, 47)
                                        .add(computeEverything)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(Clear))
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel9)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(jRadioButton4)
                                        .add(18, 18, 18)
                                        .add(jRadioButton5)))
                                .add(67, 67, 67))))
                    .add(layout.createSequentialGroup()
                        .add(159, 159, 159)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(113, 113, 113)
                        .add(jLabel2))
                    .add(layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel15)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel14)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel13)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel12)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel11)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel10))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(Basic))
                            .add(layout.createSequentialGroup()
                                .add(7, 7, 7)
                                .add(options))
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(subtotal)
                                    .add(gas)
                                    .add(tax)
                                    .add(totalrental))))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(days, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jRadioButton1)
                        .add(jRadioButton2)
                        .add(jRadioButton3)))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(coupon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(compute)
                    .add(jLabel7)
                    .add(fee))
                .add(13, 13, 13)
                .add(jLabel8)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBox1)
                    .add(jCheckBox2)
                    .add(jCheckBox3))
                .add(31, 31, 31)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jRadioButton5)
                    .add(jRadioButton4))
                .add(26, 26, 26)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(computeEverything)
                    .add(Clear))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(Basic))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(options))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(gas))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(subtotal))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(tax))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(totalrental))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daysActionPerformed

    public double computeFee(String carType, int rentalDays)
    {
        double totalFee = 0.0;
        
        //compute the fee
        if (rentalDays < 7)
        {    
        if (carType.equals("Economy"))
        {
            totalFee = rentalDays * 30;
        }
        else
        {
            if (carType.equals("midSize"))
            {
                totalFee = rentalDays *40;
            }
            else
            {
                if (carType.equals("Luxury"))
                {
                    if (couponCode.equals("LUX15OFF"))
                    {
                      totalFee = (rentalDays * 50) - 15;  
                    }
                    else
                    {    
                    totalFee = rentalDays * 50;
                    }
               }
            }    
        }
        }
        
        else
        {
            if (carType.equals("Economy"))
        {
            totalFee = rentalDays * 30;
        }
        else
        {
            if (carType.equals("midSize"))
            {
                totalFee = rentalDays *37.50;
            }
            else
            {
                if (carType.equals("Luxury"))
                {
                    if (couponCode.equals("LUX15OFF"))
                    {
                      totalFee = (rentalDays * 45) - 15;  
                    }
                    else
                    {    
                    totalFee = rentalDays * 45;
                    }
               }
            }    
        } 
        }    
        
        return totalFee;
        
    }
    
    //declare global variables
    int numDays;
    String Name, couponCode, Car;
    double total = 0.0;
    String option= "";
    double gasPrice = 0.0, subTotal = 0.0, Tax = 0.0, grandTotal = 0.0;
    
    private void computeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeActionPerformed
        // TODO add your handling code here:
        
        
        //get values vor variables
        numDays = Integer.parseInt(days.getText());
        Name = name.getText();
        couponCode = coupon.getText();
        
        if(Name.equals(""))
        {
          javax.swing.JOptionPane.showMessageDialog(null,"Please enter a name");   
        }   
        
        if (numDays == 0)
        {
           javax.swing.JOptionPane.showMessageDialog(null,"Please enter number of days");  
        }    
        else
        {    
        //call the compute fee method
        if (jRadioButton1.isSelected())
        {
            total = computeFee("Economy", numDays);
            Car = "Economy";
        }
        else
        {
            if (jRadioButton2.isSelected())
            {
                total = computeFee("midSize", numDays);
                Car = "midSize";
            }
            else
            {
                if (jRadioButton3.isSelected())
                {
                    total = computeFee("Luxury", numDays);
                    Car = "Luxury";
                }
                else
                {
                    javax.swing.JOptionPane.showMessageDialog(null,"Please select a car type");    
                }
            }
            
        }
        
        NumberFormat cf = NumberFormat.getCurrencyInstance();
        
        fee.setText(cf.format(total));
        }
        
        
        
    }//GEN-LAST:event_computeActionPerformed

    private void computeEverythingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeEverythingActionPerformed
        
        // decalre variables
        
        
        // sets the option text field based on selection
        if (option.equals(""))
        {    
            if (jCheckBox1.isSelected())
            {
            option = option + " GPS System"; 
            subTotal = total + 20;
            }
            if (jCheckBox2.isSelected())
            {
            option = option + " Extra Insurance";    
            subTotal = total + (10 * numDays);
            }
            if (jCheckBox3.isSelected())
            {
            option = option + " Child Safety Seat";  
            subTotal = total + (5 * numDays);
            }
        }
        
        options.setText(option);
        
        if (jRadioButton4.isSelected())
        {
            gasPrice = computeTotal("Yes", Car);
        }
        else
        {
            if (jRadioButton5.isSelected())
            {
               gasPrice = computeTotal("No", Car); 
            }  
            else
            {
               javax.swing.JOptionPane.showMessageDialog(null,"Please select a gas option"); 
            }    
        }    
        
        NumberFormat cf = NumberFormat.getCurrencyInstance();
        
        // compute all the variables
        subTotal = subTotal + gasPrice;
        Tax = subTotal * .0825;
        grandTotal = Tax + subTotal;
        
        // display results
        Basic.setText(cf.format(total));
        options.setText(option);
        gas.setText(cf.format(gasPrice));
        subtotal.setText(cf.format(subTotal));
        tax.setText(cf.format(Tax));
        totalrental.setText(cf.format(grandTotal));
        
    }//GEN-LAST:event_computeEverythingActionPerformed

    public double computeTotal(String gasOption, String carType)
    {
        double sub = 0.0;
        
        if (gasOption.equals("Yes"))
        {
            if(carType.equals("Economy"))
            {
                sub = 3.50 * 10;
            }
            if(carType.equals("midSize"))
            {
                sub = 3.50 * 12;
            }
            if(carType.equals("Luxury"))
            {
                sub = 3.50 * 15;
            }
        }      
       
        
        return sub;
    }        
    
    
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        // clears all variables
        numDays = 0;
        Name = ""; couponCode = ""; Car = "";
        total = 0.0; 
        gasPrice = 0.0; subTotal = 0.0; Tax = 0.0; grandTotal = 0.0;
        option = "";
        
        //resets the form
        name.setText("");
        days.setText("0");
        coupon.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        totalrental.setText("");
        tax.setText("");
        subtotal.setText("");
        gas.setText("");
        options.setText("");
        Basic.setText("");
        fee.setText("");
        jCheckBox1.setSelected(false); 
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentalCarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentalCarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentalCarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentalCarUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RentalCarUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Basic;
    private javax.swing.JButton Clear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton compute;
    private javax.swing.JButton computeEverything;
    private javax.swing.JTextField coupon;
    private javax.swing.JTextField days;
    private javax.swing.JLabel fee;
    private javax.swing.JLabel gas;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField name;
    private javax.swing.JLabel options;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel tax;
    private javax.swing.JLabel totalrental;
    // End of variables declaration//GEN-END:variables
}
